databases:
  - name: django_demo_db
    databaseName: db
    user: db

services:
  - type: web
    name: django_demo_site
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_demo_site.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_demo_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4